---
sudo: true

addons:
  apt:
    packages:
      - python
      - realpath
      - ruby

language: go

env:
  global:
    - GOLANGCI_VERSION="v1.16.0"

go:
  # Kubernetes minimum_go_version can be found in this file:
  # https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh
  - stable

install:
  - gem install asciidoctor mdl
  - pip install --user --upgrade pip
  - pip install --user yamllint
  # install dep
  - >
    curl -L
    https://raw.githubusercontent.com/golang/dep/master/install.sh
    | sh
  # install golangci-lint
  - >
    curl -sf
    "https://install.goreleaser.com/github.com/golangci/golangci-lint.sh"
    | bash -s -- -b $GOPATH/bin "${GOLANGCI_VERSION}"

script:
  # Lint text-like files
  - scripts/pre-commit.sh --require-all
  # Fetch vendor dependencies so linters succeed
  - make vendor-install
  # Lint golang sources
  - scripts/go-lint.sh
