groups:
- name: Gluster
  rules:
  # Verify gluster processes uptime is > 0
  - alert: GlusterUptime
    expr: gluster_process:gluster_elapsed_time_seconds:rate5m < 1
    for: 1m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_process.warning.gluster_elapsed_time_seconds
      summary: "{{ $labels.job }} - Gluster process {{ $labels.name }} on {{ $labels.instance }} has been down in the past 3 minute"
      description:  "{{ $labels.name }} has been detected down on node {{ $labels.instance }} belonging to cluster {{ $labels.job }} in thepast three minutes. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6001"
      dashboard: "glusterfsd: https://grafana.com/d/b5d6Bi-ik/gluster-statistics-per-brick?orgId=1 \n gluster daemon: https://grafana.com/d/Wf7HGm-mk/gluster-statistics-per-node?orgId=1"
  # Verify gluster processes cpu is < 85
  - alert: GlusterCpu
    expr: gluster_process:gluster_cpu_percentage:avg1h > 84 and gluster_process:gluster_cpu_percentage:avg1h < 95
    for: 3m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_process.warning.gluster_cpu_percentage
      summary: "{{ $labels.job }} - Gluster process {{ $labels.name }} on {{ $labels.instance }} CPU% utilization warning"
      description:  "{{ $labels.name }} on {{ $labels.instance }} belonging to cluster {{ $labels.job }} is using more than 85% CPU avg in the past hour. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6002"
      dashboard: "glusterfsd: https://grafana.com/d/b5d6Bi-ik/gluster-statistics-per-brick?orgId=1 \n gluster daemon: https://grafana.com/d/Wf7HGm-mk/gluster-statistics-per-node?orgId=1"
  # Verify gluster processes cpu is < 95
  - alert: GlusterCpu
    expr: gluster_process:gluster_cpu_percentage:avg1h > 94
    for: 3m
    labels:
      severity: critical
    annotations:
      alert_name: prometheus.gluster_process.critical.gluster_cpu_percentage
      summary: "{{ $labels.job }} - Gluster process {{ $labels.name }} on {{ $labels.instance }} CPU% utilization critical"
      description:  "{{ $labels.name }} on {{ $labels.instance }} belonging to cluster {{ $labels.job }} is using more than 95% of CPU avg in the past hour. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6002"
      dashboard: "glusterfsd: https://grafana.com/d/b5d6Bi-ik/gluster-statistics-per-brick?orgId=1 \n gluster daemon: https://grafana.com/d/Wf7HGm-mk/gluster-statistics-per-node?orgId=1"
  # Verify gluster processes memory is < 75
  - alert: GlusterMemory
    expr: gluster_process:gluster_memory_percentage:avg1h > 74 and gluster_process:gluster_memory_percentage:avg1h < 85
    for: 3m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_process.warning.gluster_memory_percentage
      summary: "{{ $labels.job }} - Gluster process {{ $labels.name }} on {{ $labels.instance }} Memory% utilization warning"
      description:  "{{ $labels.name }} on {{ $labels.instance }} belonging to cluster {{ $labels.job }} is using more than 75% of Memory avg in the past hour. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6002"
      dashboard: "glusterfsd: https://grafana.com/d/b5d6Bi-ik/gluster-statistics-per-brick?orgId=1 \n gluster daemon: https://grafana.com/d/Wf7HGm-mk/gluster-statistics-per-node?orgId=1"
  # Verify gluster processes memory is < 95
  - alert: GlusterMemory
    expr: gluster_process:gluster_memory_percentage:avg1h > 84
    for: 3m
    labels:
      severity: critical
    annotations:
      alert_name: prometheus.gluster_process.critical.gluster_memory_percentage
      summary: "{{ $labels.job }} - Gluster process {{ $labels.name }} on {{ $labels.instance }} Memory% utilization critical"
      description:  "{{ $labels.name }} on {{ $labels.instance }} belonging to cluster {{ $labels.job }} is using more than 85% of Memory for the past 3 minutes. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6002"
      dashboard: "glusterfsd: https://grafana.com/d/b5d6Bi-ik/gluster-statistics-per-brick?orgId=1 \n gluster daemon: https://grafana.com/d/Wf7HGm-mk/gluster-statistics-per-node?orgId=1"        
  # Verify gluster volume capacity utilization is < 90
  - alert: GlusterVolCapacity
    expr: gluster_volume:gluster_brick_capacity_used:percent > 89 and gluster_volume:gluster_brick_capacity_used:percent < 95
    for: 10m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_volume.warning.gluster_brick_capacity_used
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} capacity utilization warning"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} is using more than 90% of its space for 10 minutes. See the opdoc for troubleshootinga"
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
  # Verify gluster volume capacity utilization is < 95
  - alert: GlusterVolCapacity
    expr: gluster_volume:gluster_brick_capacity_used:percent > 94
    for: 10m
    labels:
      severity: critical
    annotations:
      alert_name: prometheus.gluster_volume.critical.gluster_brick_capacity_used
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} capacity utilization critical"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} is using more than 95% of its space for 10 minutes. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
  # Verify gluster volume inodes utilization is < 90
  - alert: GlusterVolInodes
    expr: gluster_volume:gluster_brick_inodes_used:percent > 89 and gluster_volume:gluster_brick_inodes_used:percent < 95
    for: 10m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_volume.warning.gluster_brick_inodes_used
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} inodes utilization warning"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} is using more than 90% of its inodes for 10 minutes. See the opdoc for troubleshooting"
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
  # Verify gluster volume inodes utilization is < 95
  - alert: GlusterVolInodes
    expr: gluster_volume:gluster_brick_inodes_used:percent > 94
    for: 10m
    labels:
      severity: critical
    annotations:
      alert_name: prometheus.gluster_volume.critical.gluster_brick_inodes_used
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} inodes utilization critical"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} is using more than 95% of its inodes for 10 minutes. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
  # Verify gluster volume cnd sub-volume capacity diff is < 1024
  - alert: GlusterVolCapacityDiff
    expr: gluster_volume:gluster_subvol_capacity_used:diff > 1023 and gluster_volume:gluster_subvol_capacity_used:diff < 4096
    for: 10m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_volume.warning.gluster_subvol_capacity_used_diff
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} capacity difference with subvolume warning"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} has a capacity difference with its subvolume of more than 1MB. See the opdoc for troubleshooting."                        
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
  # Verify gluster volume cnd sub-volume capacity diff is < 4096
  - alert: GlusterVolCapacityDiff
    expr: gluster_volume:gluster_subvol_capacity_used:diff > 4095
    for: 10m
    labels:
      severity: critical
    annotations:
      alert_name: prometheus.gluster_volume.critical.gluster_subvol_capacity_used_diff
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} capacity difference with subvolume critical"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} has a capacity difference with its subvolume of more than 4MB. See the opdoc for troubleshooting."                        
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
  # Verify gluster volume inodes utilization critical 1 week prediction
  - alert: GlusterVolInodesPrediction
    expr: gluster_volume:gluster_brick_inodes_used_percent:predict_linear1h_7d > 94
    for: 10m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_volume.warning.gluster_brick_inodes_used_prediction
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} inodes predicted utilization warning"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} is expected to be using more than 95% of its inodes in 7 days. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
  # Verify gluster volume capacity utilization is < 95
  - alert: GlusterVolCapacityPrediction
    expr: gluster_volume:gluster_brick_capacity_used_percent:predict_linear1h_7d > 94
    for: 10m
    labels:
      severity: warning
    annotations:
      alert_name: prometheus.gluster_volume.warning.gluster_brick_capacity_used_prediction
      summary: "{{ $labels.job }} - Gluster volume {{ $labels.volume }} capacity predicted utilization warning"
      description:  "Volume {{ $labels.volume }} belonging to cluster {{ $labels.job }} is expected to be using more than 95% of its space in 7 days. See the opdoc for troubleshooting."
      opdoc: "OPDOC-6003"
      dashboard: "https://grafana.com/d/S4dQMiamz/gluster-statistics-per-volume?orgId=1"
