- name: gluster_volume
  interval: 3m
  rules:
  # capacity aggr
  - record: gluster_volume:gluster_brick_capacity_total:max
    expr: max(gluster_brick_capacity_total) by (job, volume)
  - record: gluster_volume:gluster_brick_capacity_used:max
    expr: max(gluster_brick_capacity_used) by (job, volume)
  - record: gluster_volume:gluster_brick_capacity_free:min
    expr: min(gluster_brick_capacity_free) by (job, volume)
  - record: gluster_volume:gluster_subvol_capacity_used:max
    expr: max(gluster_subvol_capacity_used) by (job, volume)
  - record: gluster_volume:gluster_brick_capacity_used:percent_avg_3m
    expr: avg_over_time(gluster_volume:gluster_brick_capacity_used:max[3m]) * 100 / avg_over_time(gluster_volume:gluster_brick_capacity_total:max[3m])
  - record: gluster_volume:gluster_subvol_capacity_used:diff_avg_3m
    expr:  avg_over_time(gluster_volume:gluster_subvol_capacity_used:max[3m]) - avg_over_time(gluster_volume:gluster_brick_capacity_used:max[3m])
  # inodes aggr
  - record: gluster_volume:gluster_brick_inodes_total:max
    expr: max(gluster_brick_inodes_total) by (job, volume)
  - record: gluster_volume:gluster_brick_inodes_used:max
    expr: max(gluster_brick_inodes_used) by (job, volume)
  - record: gluster_volume:gluster_brick_inodes_free:min
    expr: min(gluster_brick_inodes_free) by (job, volume)
  - record: gluster_volume:gluster_brick_inodes_used:percent_avg_3m
    expr: avg_over_time(gluster_volume:gluster_brick_inodes_used:max[3m]) * 100 / avg_over_time(gluster_volume:gluster_brick_inodes_total:max[3m])
