{
 "title": "Gluster  Statistics per Brick",
 "description": "Dashboard for Gluster Nodes",
 "tags": [
  "gluster",
  "glusterfs"
 ],
 "time": { "from": "now-5m", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({job=~\"$cluster\"}, instance)"
   },
   {
    "name": "brick",
    "label": "Brick",
    "query": "label_values({instance=~\"$node\"}, brick_path)"
   },
   { "name": "process", "label": "Process", "query": "label_values(name) " }
  ]
 },
 "panels": [
  { "title": "Per Brick Alerting Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$process CPU % Used for $brick",
   "type": "singlestat",
   "description": "Current Gluster brick daemon CPU % used  for the given brick.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_cpu_percentage{instance=~\"[[node]]\", brick_path=\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Uptime Rate for $brick",
   "type": "singlestat",
   "description": "Gluster daemon uptime rate in the past five minutes for the given brick. A value below 1 means the daemon has been down. It is rounded to the neearest integer by Prometheus.",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_process:gluster_elapsed_time_seconds:rate5m{instance=~\"[[node]]\", brick_path=\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Memory % Used for $brick",
   "type": "singlestat",
   "description": "Current Gluster brick daemon memory % used  for the given brick.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_memory_percentage{instance=~\"[[node]]\", brick_path=\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "Avg $process CPU % for $brick",
   "type": "singlestat",
   "description": "Averae Gluster brick daemon CPU % utilization for the given brick in the past hour.",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_process:gluster_cpu_percentage:avg1h{instance=~\"[[node]]\", brick_path=\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "Avg $process Memory % Utilization for $brick",
   "type": "singlestat",
   "description": "Average Gluster brick daemon Memory % utilization for the given brick in the past hour.",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_process:gluster_memory_percentage:avg1h{instance=~\"[[node]]\", brick_path=\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  { "title": "Per Brick Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "glusterfsd CPU % for $brick",
   "type": "graph",
   "description": "Used CPU % reported by brick in the given node",
   "gridPos": { "h": 10, "w": 10, "x": 2, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "gluster_cpu_percentage{job=~\"[[cluster]]\", instance=~\"[[node]]\", brick_path=~\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Uptime for $node",
   "type": "singlestat",
   "description": "Gluster  brick daemon uptime for the given node.",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_elapsed_time_seconds{instance=~\"[[node]]\", brick_path=\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "glusterfsd Memory % for $brick",
   "type": "graph",
   "description": "Gluster memory utilization % reported by brick in the given node",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "gluster_memory_percentage{job=~\"[[cluster]]\", instance=~\"[[node]]\", brick_path=~\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "glusterfsd Resident Memory for $brick",
   "type": "graph",
   "description": "Gluster  resident memory utilization reported by brick in the given node",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_resident_memory{job=~\"[[cluster]]\", instance=~\"[[node]]\", brick_path=~\"[[brick]]\", name=\"[[process]]\"}",
     "legendFormat": "$brick"
    }
   ]
  },
  {
   "title": "glusterfsd Virtual Memory for $brick",
   "type": "graph",
   "description": "Gluster  virtual memory utilization reported by brick in the given node",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_virtual_memory{job=~\"[[cluster]]\", instance=~\"[[node]]\", brick_path=~\"[[brick]]\", name=\"[[process]]\"}"
    }
   ]
  }
 ]
}