{
 "title": "Gluster  Statistics per Node",
 "description": "Dashboard for Gluster Nodes",
 "tags": [
  "gluster",
  "glusterfs"
 ],
 "time": { "from": "now-5m", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({job=~\"$cluster\"}, instance)"
   },
   { "name": "process", "label": "Process", "query": "label_values(name) " }
  ]
 },
 "panels": [
  { "title": "Per Node Alerting Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$process CPU Used for $node",
   "type": "singlestat",
   "description": "Gluster daemon CPU % used  for the given node.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_cpu_percentage{instance=~\"[[node]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Uptime for $node",
   "type": "singlestat",
   "description": "Gluster daemon uptime for the given node.",
   "gridPos": { "h": 7, "w": 11, "x": 7, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_elapsed_time_seconds{instance=~\"[[node]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Memory Used for $node",
   "type": "singlestat",
   "description": "Gluster daemon memory % used  for the given node.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_memory_percentage{instance=~\"[[node]]\", name=\"[[process]]\"}"
    }
   ]
  },
  { "title": "Per Node Metrics Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$process CPU % for $node",
   "type": "graph",
   "description": "Gluster Daemon Used CPU % reported by node in the given cluster.",
   "gridPos": { "h": 10, "w": 10, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_cpu_percentage{job=~\"[[cluster]]\", instance=~\"[[node]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Uptime for $node",
   "type": "graph",
   "description": "Gluster daemon uptime in seconds reported by each node in the given cluster",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "gluster_elapsed_time_seconds{job=~\"[[cluster]]\", instance=~\"[[node]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Memory % for $node",
   "type": "graph",
   "description": "Gluster daemon memory utilization % reported by node in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "gluster_memory_percentage{job=~\"[[cluster]]\", instance=~\"[[node]]\", name=\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Resident Memory for $node",
   "type": "graph",
   "description": "Gluster  daemon resident memory utilization reported by node in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_resident_memory{job=~\"[[cluster]]\", instance=~\"[[node]]\", name=~\"[[process]]\"}"
    }
   ]
  },
  {
   "title": "$process Virtual Memory for $node",
   "type": "graph",
   "description": "Gluster  daemon virtual memory utilization reported by node in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_virtual_memory{job=~\"[[cluster]]\", instance=~\"[[node]]\", name=~\"[[process]]\"}"
    }
   ]
  }
 ]
}