{
 "title": "Gluster  Statistics per Volume",
 "description": "Dashboard for Gluster Volumes",
 "tags": [
  "gluster",
  "glusterfs"
 ],
 "time": { "from": "now-5m", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "volume",
    "label": "Volume",
    "query": "label_values({job=~\"$cluster\"}, volume)"
   },
   {
    "name": "brick",
    "label": "Brick",
    "query": "label_values({volume=~\"$volume\"}, brick_path)"
   }
  ]
 },
 "panels": [
  { "title": "Per Volume Alerting Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume $volume % Capacity Used",
   "type": "singlestat",
   "description": "Percentage of used space for the given volume over a period of three minutes",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_capacity_used:percent_avg_3m{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Sub-Volume Capacity Difference for $volume",
   "type": "singlestat",
   "description": "Difference between the subvolume used capacity and the brick used capacity over a 3 minutes period",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_volume:gluster_subvol_capacity_used:diff_avg_3m{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Volume $volume % Inodes Used",
   "type": "singlestat",
   "description": "Percentage of used inodes in the given volume over a period of three minutes.",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_inodes_used:percent_avg_3m{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  { "title": "Per Volume Metrics Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Used  Capacity for $volume",
   "type": "graph",
   "description": "Used capacity reported by volume in the given cluster.\nThis metric is the maximum value aggregated by cluster and volume",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_capacity_used:max{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Used Sub-volume Capacity for $volume",
   "type": "graph",
   "description": "Used sub-volume capacity in the given cluster.\nThis metric is the maximum value aggregated by cluster and volume",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_volume:gluster_subvol_capacity_used:max{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Used Inodes for $volume",
   "type": "graph",
   "description": "Used inodes reported by volume in the given cluster.\nThis metric is the maximum value aggregated by cluster and volume",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_inodes_used:max{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Total Capacity  for $volume",
   "type": "graph",
   "description": "Total volume capacity in the given cluster.\nThis metric is the maximum value aggregated by cluster and volume",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_capacity_total:max{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Free  Capacity for $volume",
   "type": "graph",
   "description": "Free volume capacity reported in the given cluster.\nThis metric is the minimum value aggregated by cluster and volume",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_capacity_free:min{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Total  Inodes for $volume",
   "type": "graph",
   "description": "Total  inodes reported by volume in the given cluster.\nThis metric is the maximum value aggregated by cluster and volume",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_capacity_total:max{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  {
   "title": "Free Inodes for $volume",
   "type": "graph",
   "description": "Free inodes reported by volume in the given cluster.\nThis metric is the minimum value aggregated by cluster and volume",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volume:gluster_brick_inodes_free:min{job=~\"[[cluster]]\", volume=~\"[[volume]]\"}"
    }
   ]
  },
  { "title": "Per Brick Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total Brick Capacity  for $brick",
   "type": "graph",
   "description": "Total brick capacity reported by brick in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_capacity_total{job=~\"[[cluster]]\", brick_path=~\"[[brick]]\"}"
    }
   ]
  },
  {
   "title": "Free Brick Capacity for $brick",
   "type": "graph",
   "description": "Free brick capacity reported by brick in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_capacity_free{job=~\"[[cluster]]\", brick_path=~\"[[brick]]\"}"
    }
   ]
  },
  {
   "title": "Used Brick Capacity for $brick",
   "type": "graph",
   "description": "Used brick capacity reported by brick in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_capacity_used{job=~\"[[cluster]]\", brick_path=~\"[[brick]]\"}"
    }
   ]
  },
  {
   "title": "Total Brick Inodes for $brick",
   "type": "graph",
   "description": "Total brick inodes reported by brick in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_inodes_total{job=~\"[[cluster]]\", brick_path=~\"[[brick]]\"}"
    }
   ]
  },
  {
   "title": "Free Brick Inodes for $brick",
   "type": "graph",
   "description": "Free brick inodes reported by each brick in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_inodes_free{job=~\"[[cluster]]\", brick_path=~\"[[brick]]\"}"
    }
   ]
  },
  {
   "title": "Used Brick Inodes for $brick",
   "type": "graph",
   "description": "Used brick inodes reported by brick in the given cluster",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_inodes_used{job=~\"[[cluster]]\", brick_path=~\"[[brick]]\"}"
    }
   ]
  }
 ]
}